#!/usr/bin/with-contenv bash
# ==============================================================================
# Mosquitto MQTT Broker
# Sets permissions before running
# ==============================================================================

set -e

cp /etc/mosquitto/include_dir.conf /app/include_dir.conf

CONFIG_FILE=/app/config/mosquitto.conf
if [ ! -f "${CONFIG_FILE}" ]; then
	cp /etc/mosquitto/mosquitto.conf ${CONFIG_FILE}
fi

# Set permissions
user="$(id -u)"
if [ "$user" = '0' ]; then
	[ -d "/app" ] && chown -R mosquitto:mosquitto /app || true
fi