#!/usr/bin/with-contenv bash
# ==============================================================================
# Mosquitto MQTT Broker
# Starts Mosquitto
# ==============================================================================

echo "Starting Mosquitto..."

cd /usr/sbin
exec mosquitto -c /app/config/mosquitto.conf